app/controllers/auto_report.py
import arrow
import sqlparse
from dateutil import tz
from flask import Blueprint
from flask import abort
from flask import current_app as app
from flask import render_template, request, jsonify
from flask_login import login_required
from sqlalchemy import text
from validate_email import validate_email

from app.extensions import db
from app.models.main import permission_required
from app.models.scheduled_report import ScheduledReport
from app.utils import error_msg_from_exception

auto_report = Blueprint('auto_report', __name__)


@auto_report.route("/auto_reports/display", methods=["GET"])
@login_required
@permission_required('manager')
def report_display_panel():
    reports = db.session.query(ScheduledReport).all()
    return render_template('auto_report/reports_display.html', reports=reports)


@auto_report.route("/auto_report/<report_name>", methods=["GET"])
@login_required
@permission_required('manager')
def report_edit_panel(report_name):
    report = ScheduledReport.get_report(report_name).one()
    if report is None:
        return abort(404)

    return render_template('auto_report/report_editing.html', report=report)


@auto_report.route("/auto_reports/operate", methods=['GET', 'POST', 'PUT', 'DELETE'])
@login_required
@permission_required('manager')
def report_operate_panel():
    if request.method == 'GET':
        return render_template('auto_report/report_create.html')

    elif request.method == 'POST':

        sql = request.form.get('sql')
        report_name = request.form.get('report_name')
        description = request.form.get('description').strip()
        scheduled_at = request.form.get('scheduled_at')
        maximum_count = request.form.get('maximum_count')
        rearm = request.form.get('rearm')
        formatted_sql = sqlparse.format(sql.strip().strip(';'), reindent=True, keyword_case='upper')
        database = request.form.get('database')
        recipients = request.form.get('recipients')

        test_email_address = recipients.split(',')

        if len(test_email_address) > 10:
            return jsonify(error="Can't be exceeding 10"), 500

        invalid_addresses = [email_address for email_address in test_email_address if not validate_email(email_address)]

        if invalid_addresses:
            invalid_addresses = ','.join(invalid_addresses)
            return jsonify(error=invalid_addresses + ' is Invalid'), 500

        def evaluate_sql(sql, database):
            stmt = sqlparse.parse(sql)[0]
            tokens = [str(item) for item in stmt.tokens]
            slim_sql = ''.join(tokens)
            if database == 'bi':
                database = None

            result_proxy = db.get_engine(db.get_app(), bind=database).execute(text(slim_sql))

            sql_tokens = [str(tokens).upper() for tokens in [tokens for tokens in stmt.tokens if tokens.is_keyword]]
            sql_limit = any(
                [tokens in ['INSERT', 'UPDATE', 'DELETE', 'USE', 'DROP', 'TRUNCATE'] for tokens in sql_tokens])

            if sql_limit:
                return False, "Your SQL statements are not allowed against this database"
            else:

                return True, 'ok'

        try:
            is_valid_sql, alert = evaluate_sql(formatted_sql, database)

            if is_valid_sql:

                report = ScheduledReport.get_report(report_name).delete()

                scheduled_at_utc = arrow.get(scheduled_at).replace(tzinfo=tz.gettz(app.config['APP_TIMEZONE'])).to(
                    'UTC')

                report = ScheduledReport(sql=sql,
                                         database=database,
                                         recipients=recipients,
                                         report_name=report_name,
                                         description=description,
                                         is_activated=False,
                                         is_paused=False,
                                         scheduled_at=scheduled_at_utc.format('YYYY-MM-DD HH:mm:ss'),
                                         maximum_count=maximum_count,
                                         rearm=rearm)
                db.session.add(report)
                db.session.commit()

                return jsonify(message=alert), 200

            else:

                return jsonify(error=alert), 500

        except Exception as e:

            return jsonify(error=error_msg_from_exception(e)), 500

    elif request.method == 'DELETE':
        report_id = request.form.get('report_id', type=int)

        report = db.session.query(ScheduledReport).filter_by(id=report_id)
        report.delete()
        db.session.commit()
        return jsonify(message='ok'), 200
    elif request.method == 'PUT':
        report_id = request.form.get('report_id', type=int)
        operate = request.form.get('operate')

        try:
            report = db.session.query(ScheduledReport).filter_by(id=report_id).one()
        except:
            return jsonify(message='not found'), 200

        else:

            if operate == 'activate':
                report.is_activated = True
                report.is_paused = False
                db.session.flush()
                db.session.commit()
                return jsonify(message='ok'), 200
            if operate == 'pause':
                report.is_paused = True
                db.session.flush()
                db.session.commit()
                return jsonify(message='ok'), 200
    else:
        return abort(404)

app/templates/auto_report/report_create.html
{% extends "layout/app.html" %}

{% block page_title %}Auto Report{% endblock %}

{% block head_tail %}

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.25/daterangepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/codemirror.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/codemirror.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/addon/hint/show-hint.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">

{% endblock %}

{% block main_content %}

    <section class="content-header">
        <h1 id="report-title">
            Create New Report
        </h1>
    </section>

    <section class="content">
        <div class="box box-danger" id="editor-box">
            <div class="box-header with-border">
                <h3 class="box-title">Report Options </h3>


                <a style="margin-left: 10px" class="btn btn-primary pull-right"
                   href="/auto_reports/display">

                    <i class="fa fa-reply"></i> </a>

                <a id='report-save' class="btn btn-primary pull-right" style="display: inline-block"> <i
                        class="fa fa-save"></i> Save </a>

                <a id='report-edit' class="btn btn-primary pull-right" style="display: none"> <i class="fa fa-edit"></i>
                    Edit </a>


            </div>
            <fieldset id="disable-me">

                <div class="box-body">


                    <div class="row">
                        <div class="col-md-4">

                            <div class="form-group">
                                <label>Report Name</label>
                                <input id="report-name" type="text" class="form-control" placeholder="Enter ...">
                            </div>

                            <div class="form-group">
                                <label>Description</label>
                                <textarea id='report-description' class="form-control" rows="12"
                                          style="font-size: 16px"></textarea>


                            </div>


                            <div class="form-group">

                                <label> Recipients </label>

                                <div class="form-group">

                                    <input name="testEmail" type="text" class="form-control" spellcheck="false"

                                           id='recipients'

                                           data-toggle="tooltip" data-animation="false"

                                           data-title="Enter up to 10 addresses at once, separated by a comma."

                                           data-original-title="" title="">
                                </div>

                            </div>


                            <div class="form-group">
                                <label> Scheduled At (EST) </label>
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                    <input name="scheduled" type="text" class="form-control" id="send-scheduled-at">
                                </div>
                            </div>

                            <div class="form-group">

                                <label>Rearm/Hour </label>
                                <input class="form-control" id="rearm" type="number" min="0">

                            </div>
                            <div class="form-group">
                                <label>Maximum Count</label>
                                <input id="maximum-count" class="form-control input-sm" type="number" min="0">
                            </div>


                        </div>

                        <div class="col-md-8">
                            <div class="form-group">
                                <label>SQL</label>
                                <select class="form-control select2" style="width: 20%; margin-bottom: 10px"
                                        id="database-picker">
                                    <option value="bi" selected="selected">DB: BI</option>
                                    <option value="bi_lifetime">DB: BI_LIFETIME</option>
                                    <option value="bi_promotion">DB: BI_PROMOTION</option>
                                    <option value="orig_wpt">DB: WPT</option>
                                    <option value="orig_wpt_ods">DB: WPT ODS</option>
                                    <option value="orig_wpt_mall">DB: WPT MALL</option>
                                    <option value="wpt_log">DB: WPT Log</option>
                                    <option value="orig_wpt_master_points">DB: MASTER POINTS</option>
                                </select>

                                <textarea id="sql-editor" class="form-control"
                                          placeholder="Enter your query"></textarea>

                            </div>


                        </div>


                    </div>
                </div>


            </fieldset>


        </div>


    </section>

{% endblock %}
{% block body_tail %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.25/daterangepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/mode/sql/sql.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/addon/hint/sql-hint.min.js"></script>
    <script>

        $(document).ready(function () {

            ///////////////Utils////////////////////////
            $(".select2").select2();
            var loadingOverlayConfig = {
                image: '',
                fontawesome: 'fa fa-spinner fa-spin',
                maxSize: "26px",
                minSize: "26px"
            };

            function startRequestLoading() {
                $('#editor-box').LoadingOverlay('show', loadingOverlayConfig);
            }

            function stopRequestLoading() {
                $('#editor-box').LoadingOverlay('hide', true);
            }

            $('#send-scheduled-at').daterangepicker({
                opens: 'right',
                showDropdowns: true,
                autoApply: true,
                singleDatePicker: true,
                timePicker: true,
                timePicker24Hour: true,
                locale: {
                    format: 'YYYY-MM-DD HH:mm:ss',
                },
                minDate: moment()
            });
            var editor = CodeMirror.fromTextArea(document.getElementById('sql-editor'), {
                mode: 'text/x-mysql',
                lineNumbers: true,
                matchBrackets: true,
                autofocus: true,
                indentUnit: 4,
                extraKeys: {"Ctrl": "autocomplete"},
                hint: CodeMirror.hint.sql,
                hintOptions: {
                    tables: {
                        bi_user_currency: {{ get_columns_of_table('app.models.bi', 'BIUserCurrency') | safe }},
                        bi_user: {{ get_columns_of_table('app.models.bi', 'BIUser') | safe }}
                    }
                }
            });
            ////////////////////////////////////////////////////////////

            $('#report-save').on('click', function () {

                if (editor.getValue().length === 0
                    || $('#report-name').val() === ""
                    || $('#send-scheduled-at').val() === ""
                    || $('#rearm').val() === ""
                    || $('#maximum-count').val() === ""
                    || $('#recipients').val() === ""
                    || $('#valid-count').val() === "") return;

                startRequestLoading();

                $.ajax({
                    type: 'POST',
                    url: "{{ url_for('auto_report.report_operate_panel') }}",
                    data: {

                        scheduled_at: $('#send-scheduled-at').val(),
                        report_name: $('#report-name').val(),
                        description: $('#report-description').val(),
                        recipients: $('#recipients').val(),

                        rearm: $('#rearm').val(),
                        maximum_count: $('#maximum-count').val(),
                        is_important: $('#is-important').is(":checked"),
                        sql: editor.getValue(),
                        database: $('#database-picker').find(":selected").val()
                    },
                    dataType: 'json',
                    success: function (result) {
                        stopRequestLoading();
                        $('#report-save').hide();
                        $("#disable-me").attr("disabled", "disabled");
                        $('#database-picker').select2('enable', false);
                        $('#report-edit').show();
                        $('#report-title').text($('#report-name').val());

                    },
                    error: function (xhr) {
                        stopRequestLoading();
                        alert(JSON.parse(xhr.responseText).error)

                    }
                })


            });
            $('#report-edit').on('click', function () {

                $(this).hide();
                $('#report-save').show();
                $('#database-picker').select2('enable');
                $('#disable-me').removeAttr('disabled');
            });

        });

    </script>
{% endblock %}

app/templates/auto_report/reports_display.html
{% extends "layout/app.html" %}

{% block page_title %}Auto Report{% endblock %}

{% block head_tail %}

{% endblock %}

{% block main_content %}

    <section class="content">

        <div class="row">

            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border" style=" padding-bottom: 10px; padding-top: 25px; ">

                        <h3 class="box-title" style="margin-left: 10px">{{ push_type }} Automation Report</h3>


                        <a class="btn btn-primary pull-right"
                           href="{{ url_for('auto_report.report_operate_panel') }}"
                           title="Create new Report" style="display: inline-block"> <i
                                class="fa fa-plus-circle"></i>
                            Create
                        </a>

                    </div>

                    <div class="box-body" style=" padding-right: 80px; padding-left: 20px; ">

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Report Name</th>
                                <th><strong> Description </strong></th>
                                <th><strong> Status </strong></th>
                                <th><strong> Rearm / Hour</strong></th>
                                <th><strong> Remaining Times </strong></th>
                                <th><strong> Scheduled At </strong></th>
                                <th><strong>Actions </strong></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for report in reports %}


                                <tr id="{{ report.id }}">
                                    <td>
                                        <strong>


                                            <a href="{{ url_for('auto_report.report_edit_panel', report_name= report.report_name ) }}">{{ report.report_name }}</a>


                                        </strong>

                                    <td>
                                        <p>
                                            {{ report.description }}
                                        </p>
                                    <td>


                                        {% if report.remaining_count == 0 %}

                                            <span class="badge ">Expired</span>

                                        {% elif not report.is_activated %}

                                            <span class="badge bg-blue"> Inactivated </span>

                                        {% elif report.is_paused %}

                                            <span class="badge bg-yellow">Paused</span>

                                        {% else %}

                                            <span class="badge bg-green">Activate</span>

                                        {% endif %}

                                    </td>
                                    <td>
                                        {{ report.rearm }}
                                    </td>

                                    <td>

                                        {{ report.remaining_count }}

                                    </td>
                                    <td>
                                        {{ report.scheduled_at }}
                                    </td>
                                    <td>

                                        <div class="btn-group">
                                            <button type="button" class="btn btn-box-tool dropdown-toggle"
                                                    data-toggle="dropdown" aria-expanded="">
                                                <i class="ion ion-ios-gear-outline" style="font-size: 25px; "></i>
                                            </button>

                                            <ul class="dropdown-menu" role="menu">


                                                {% if report.remaining_count == 0 %}

                                                    <li><a data-report-id="{{ report.id }}" class="delete">Delete</a>
                                                    </li>


                                                {% else %}


                                                    <li><a data-report-id="{{ report.id }}"
                                                           class="activate">Activate</a></li>
                                                    <li><a data-report-id="{{ report.id }}" class="pause">Pause</a></li>
                                                    <li><a data-report-id="{{ report.id }}" class="delete">Delete</a>
                                                    </li>

                                                {% endif %}


                                            </ul>


                                        </div>

                                    </td>

                                </tr>

                            {% endfor %}

                            </tbody>
                        </table>

                    </div>
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                        </ul>
                    </div>

                </div>
            </div>
        </div>

    </section>

{% endblock %}

{% block body_tail %}

    <script>

        $(document).ready(function () {


            var url = "{{ url_for('auto_report.report_operate_panel') }}";


            var loadingOverlayConfig = {
                image: '',
                fontawesome: 'fa fa-spinner fa-spin',
                maxSize: "26px",
                minSize: "26px"
            };

            ////////////////////////////////////////////////////////////

            $('.delete').on('click', function () {

                var reportId = $(this).attr("data-report-id");
                var tr = $('#' + reportId);

                tr.LoadingOverlay('show', loadingOverlayConfig);
                $.ajax({
                    type: 'DELETE',
                    url: url,
                    data: {report_id: reportId},
                    dataType: 'json',
                    success: function (result) {

                        tr.LoadingOverlay('hide', true);
                        tr.children("td").remove()

                    },
                    error: function (xhr) {
                        alert(JSON.parse(xhr.responseText).error);
                        tr.LoadingOverlay('hide', true);
                    }
                })

            });

            ////////////////////////////////////////////////////////////

            $('.pause').on('click', function () {

                var reportId = $(this).attr("data-report-id");

                var tr = $('#' + reportId);

                tr.LoadingOverlay('show', loadingOverlayConfig);
                $.ajax({
                    type: 'PUT',
                    url: url,
                    data: {report_id: reportId, operate: 'pause'},
                    dataType: 'json',
                    success: function (result) {

                        tr.LoadingOverlay('hide', true);
                        tr.children("td").eq(2).replaceWith('<td><span class="badge bg-yellow">Paused</span></td>')
                    },
                    error: function (xhr) {
                        alert(JSON.parse(xhr.responseText).error);
                        tr.LoadingOverlay('hide', true);
                    }
                })

            });

            ////////////////////////////////////////////////////////////

            $('.activate').on('click', function () {

                var reportId = $(this).attr("data-report-id");
                var tr = $('#' + reportId);

                tr.LoadingOverlay('show', loadingOverlayConfig);
                $.ajax({
                    type: 'PUT',

                    url: url,

                    data: {report_id: reportId, operate: 'activate'},

                    success: function (result) {

                        tr.LoadingOverlay('hide', true);
                        tr.children("td").eq(2).replaceWith('<td><span class="badge bg-green">Activate</span></td>')

                    },
                    error: function (xhr) {
                        alert(JSON.parse(xhr.responseText).error);

                        tr.LoadingOverlay('hide', true);
                    }
                })

            });


        });

    </script>

{% endblock %}